Drops Django upper bound limit
surface-security/django-dkron pull request #13
Opened 2022-10-04 21:11 UTC by gsilvapt

This change facilitates integrating this project into others by removing the Django < 4 restriction. 3.2.16 is LTS though, at the time of writing.

If we need the pin for a particular reason, please let's document that need in the project somewhere.

2022-10-04 21:24 UTC, DDuarte requested changes
django 4.1.2 should be added to https://github.com/surface-security/django-dkron/blob/fb5440b3adee3c05fe201b15f3665a1699ce3879/tox.ini#L10

2022-10-04 22:38 UTC, DDuarte approved these changes
not aware of Django 4 incompatibilities, lgtm

2023-01-22 16:37 UTC, fopina commented
This goes against #6 
Major version bumps in Django are usually filled with breaking changes.

We should try to allow packages only to be installed with major versions that we did test (and not necessarily trust test coverage) otherse we'll have open bug reports like #5

2023-01-22 16:39 UTC, fopina requested changes
This goes against #6 
Major version bumps in Django are usually filled with breaking changes.

We should try to allow packages only to be installed with major versions that we did test (and not necessarily trust test coverage) otherse we'll have open bug reports like #5 

Just checking if you were aware of these (issue and pull request)

2023-01-22 21:56 UTC, gsilvapt commented
Thanks! No, I didn't know these issues. Perhaps it makes sense to document these incompatibilties in the README. Do you know which specific changes are backward incompatible? While on it, is incompatible from upstream (Django) or this app? If the latter, perhaps we can do the necessary changes to make it work? 🤷‍♂️

2023-01-22 22:12 UTC, fopina commented
I only meant in general, having gone through django 1to2 and 2to3 migrations.  
I haven’t tried django 4 yet, only that issue (which doesn’t really provide details).

I would say that for any given app, if we’re happy with the test coverage, we could rely on it; but in this case it’s clear coverage wasn’t enough.

I suppose we’d have to try django 4 with the test app and understand what is not working exactly. And then create a regression test for that, in case we make the changes to support django 4

2023-01-24 13:26 UTC, gsilvapt commented
Dropping this PR for now, as discussed above, until we have some form of integration tests.
For the time being, I'll just try to add support for python 3.11 and stick with the Django <4 pin.

2023-01-24 13:26 UTC, closed without merging